services:
  backend:
    build: ./backend
    container_name: hse-backend-container
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    networks:
      - hse-app-net
      - hse-iot-net

  frontend:
    build: ./frontend
    container_name: hse-frontend-container
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hse-app-net

volumes:
  uploads_data:
    driver: local
  logs_data:
    driver: local

networks:
  hse-app-net:
    driver: bridge
  hse-iot-net:
    driver: bridge